rawExtracts/unpackaged/objects/Driver_Care_Settings__mdt.object
<CustomObject>
    <description>Holds all configurable settings for the Salesforce Care for Industries - Transport and Logistics package</description>
    <fields>
        <fullName>Default_Return_to_work_days__c</fullName>
        <defaultValue>14</defaultValue>
        <description>The number of days to add to the Work Stoppage Date to determine the Estimated Return to work date</description>
        <label>Default Return to work days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SMS_Validation_RegEx__c</fullName>
        <description>For Login discovery, specifies the Regular Expression used to validate the input SMS number</description>
        <label>SMS_Validation_RegEx</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Driver Care Setting</label>
    <pluralLabel>Driver Care Settings</pluralLabel>
</CustomObject>

mdapipack/converted/main/default/classes/DriverCareSettingsHelper.cls
public with sharing class DriverCareSettingsHelper {

    private static DriverCareSettingsHelper instance = null;
    private static final String defaultRecordName = 'default';
    public Driver_Care_Settings__mdt customMetadata {get; private set;}


    private DriverCareSettingsHelper() {
      // TODO - query and get the custom metadata type and all it's fields...
      customMetadata = [SELECT Default_Return_to_work_days__c, SMS_Validation_RegEx__c FROM Driver_Care_Settings__mdt WHERE DeveloperName = :defaultRecordName];
    }

    public static DriverCareSettingsHelper getInstance() {
      if (instance == null) {
        instance = new DriverCareSettingsHelper();
      }

      return instance;
    }
}